#ifndef POKEBW2_BATTLE_BTL_ABILITY_H
#define POKEBW2_BATTLE_BTL_ABILITY_H

#include "types.h"
#include "battle/btl_event.h"
#include "struct_decls.h"

u32 numHandlersWithHandlerPri(u32 priority, u32 count);
u32 devideNumHandersAndPri(u32 *packed);
u16 calcAbilHandlerSubPriority(BattleMon *mon);
BOOL func_ov167_021abdf8(BtlServerFlow *flow, u32 value);
BOOL AbilityEvent_RollEffectChance(BtlServerFlow *flow, u32 chance);
void AbilityEvent_ItemRotationSleep(BattleMon *mon);
void AbilityEvent_ItemRotationWake(BattleMon *mon);
void AbilityEvent_Swap(BattleMon *first, BattleMon *second);
const BattleEventHandlerEntry *EventAddIntimidate(u32 *priority);
void HandlerIntimidateMemberIn(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddInnerFocus(u32 *priority);
void HandlerInnerFocus(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddSteadfast(u32 *priority);
void HandlerSteadfast(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddThickFat(u32 *priority);
void HandlerThickFat(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddHugePower(u32 *priority);
void HandlerHugePower(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerSwiftSwim(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddSwiftSwim(u32 *priority);
void HandlerChlorophyll(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddChlorophyll(u32 *priority);
void HandlerQuickFeet(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddQuickFeet(u32 *priority);
void HandlerTangledFeet(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddTangledFeet(u32 *priority);
void HandlerHustleAccuracy(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerHustlePower(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddHustle(u32 *priority);
void HandlerStall(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddStall(u32 *priority);
void HandlerCompoundEyes(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddCompoundEyes(u32 *priority);
void HandlerSandVeil(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerSandVeilWeather(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddSandVeil(u32 *priority);
void HandlerSnowCloak(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerSnowCloakWeather(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddSnowCloak(u32 *priority);
void CommonWeatherGuard(BattleEventItem *item, BtlServerFlow *flow, u32 monId, u32 *work, u8 weather);
void HandlerTintedLens(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddTintedLens(u32 *priority);
void HandlerSolidRock(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddSolidRock(u32 *priority);
void HandlerSniper(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddSniper(u32 *priority);
void HandlerSpeedBoost(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddSpeedBoost(u32 *priority);
void HandlerAdaptability(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddAdaptability(u32 *priority);
void HandlerBlaze(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddBlaze(u32 *priority);
void HandlerTorrent(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddTorrent(u32 *priority);
void HandlerOvergrow(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddOvergrow(u32 *priority);
void HandlerSwarm(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddSwarm(u32 *priority);
void CommonLowHPBoostAbility(BtlServerFlow *flow, u8 monId, u32 type);
void HandlerGuts(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddGuts(u32 *priority);
void HandlerPlusMinus(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddPlusMinus(u32 *priority);
BOOL func_ov167_021be5c4(BtlServerFlow *flow, u8 monId, u8 *mons, u32 ability);
BOOL CheckFlowerGiftEnablePokemon(BtlServerFlow *flow, u8 monId);
void HandlerFlowerGiftMemberOnField(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerFlowerGiftGotAbility(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void CommonFlowerGiftFormChange(BattleEventItem *item, BtlServerFlow *flow, u8 monId, u8 sunny, u8 cause);
void HandlerFlowerGiftWeather(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerFlowerGiftAbilityOff(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerFlowerGiftAirLock(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerFlowerGiftAbilityChange(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerFlowerGiftPower(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerFlowerGiftSpecialDefense(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddFlowerGift(u32 *priority);
void HandlerRivalry(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddRivalry(u32 *priority);
void HandlerTechnician(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddTechnician(u32 *priority);
void HandlerIronFist(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddIronFist(u32 *priority);
void HandlerReckless(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddReckless(u32 *priority);
void HandlerMarvelScale(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddMarvelScale(u32 *priority);
void HandlerSkillLink(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddSkillLink(u32 *priority);
const BattleEventHandlerEntry *EventAddHyperCutter(u32 *priority);
void HandlerHyperCutterCheck(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerHyperCutterGuard(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddKeenEye(u32 *priority);
void HandlerKeenEyeCheck(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerKeenEyeGuard(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddClearBody(u32 *priority);
void HandlerClearBodyCheck(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerClearBodyGuard(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void CommonStatDropGuardCheck(BtlServerFlow *flow, u32 monId, u32 *result, u32 stat);
void CommonStatDropGuardFixed(BtlServerFlow *flow, u32 monId, u32 *result, u16 message);
void HandlerSimple(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddSimple(u32 *priority);
void HandlerLeafGuard(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerLeafGuardYawnCheck(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddLeafGuard(u32 *priority);
BOOL HandlerCommonGuardStatus(void *flow, u32 monId, u32 status);
void CommonAbilityCureStatus(BtlServerFlow *flow, u8 monId, u32 status);
void CommonAbilityCureStatusCore(BtlServerFlow *flow, u8 monId, u32 status);
void HandlerLimberStatus(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerLimberCureStatus(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerLimberActionEnd(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddLimber(u32 *priority);
void HandlerInsomniaStatus(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerInsomniaWake(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerInsomniaActionEnd(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerInsomniaYawnCheck(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddInsomnia(u32 *priority);
void HandlerMagmaArmorStatus(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerMagmaArmorCureStatus(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerMagmaArmorActionEnd(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddMagmaArmor(u32 *priority);
void HandlerImmunity(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerImmunityCureStatus(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerImmunityActionEnd(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddImmunity(u32 *priority);
void HandlerWaterVeil(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerWaterVeilCureStatus(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerWaterVeilActionEnd(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddWaterVeil(u32 *priority);
void HandlerOwnTempoStatus(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerOwnTempoAddStatusFailed(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerOwnTempoCureStatus(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerOwnTempoActionEnd(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddOwnTempo(u32 *priority);
void HandlerOblivious(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerObliviousCureStatus(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerObliviousActionEnd(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerObliviousNoEffectCheck(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddOblivious(u32 *priority);
void CommonAddStatusFailed(BattleEventItem *item, BtlServerFlow *flow, u32 monId, u32 *result, u16 message);
void HandlerAddStatusFailedCommon(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerDrizzle(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddDrizzle(u32 *priority);
void HandlerDrought(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddDrought(u32 *priority);
void HandlerSandStream(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddSandStream(u32 *priority);
void HandlerSnowWarning(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddSnowWarning(u32 *priority);
void CommonWeatherChangeAbility(BtlServerFlow *flow, u32 monId, u32 weather);
void HandlerAirLockMemberIn(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerAirLockChangeWeather(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddAirLock(u32 *priority);
void HandlerIceBody(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddIceBody(u32 *priority);
void HandlerRainDish(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddRainDish(u32 *priority);
void CommonWeatherRecoveryAbility(BtlServerFlow *flow, u8 monId, u32 weather);
void HandlerSolarPowerWeather(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerSolarPowerPower(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddSolarPower(u32 *priority);
void HandlerShieldDustStatus(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerShieldDustRank(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerShieldDustShrink(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerShieldDustGuard(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerShieldDustGuardHitEnd(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddShieldDust(u32 *priority);
void HandlerSereneGrace(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerSereneGraceShrink(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddSereneGrace(u32 *priority);
void HandlerHydration(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddHydration(u32 *priority);
void HandlerShedSkin(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddShedSkin(u32 *priority);
void HandlerPoisonHeal(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddPoisonHeal(u32 *priority);
void HandlerBattleArmor(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddBattleArmor(u32 *priority);
void HandlerSuperLuck(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddSuperLuck(u32 *priority);
void HandlerAngerPoint(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddAngerPoint(u32 *priority);
void HandlerPoisonPoint(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddPoisonPoint(u32 *priority);
void HandlerStatic(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddStatic(u32 *priority);
void HandlerFlameBody(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddFlameBody(u32 *priority);
void HandlerRockHead(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddRockHead(u32 *priority);
void HandlerNormalize(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddNormalize(u32 *priority);
const BattleEventHandlerEntry *EventAddTrace(u32 *priority);
void HandlerNaturalCure(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddNaturalCure(u32 *priority);
void HandlerUnawareHitRank(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerUnawareAttackRank(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerUnawareDefenseRank(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddUnaware(u32 *priority);
void HandlerScrappy(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddScrappy(u32 *priority);
void HandlerHeatproofPower(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerHeatproofStatus(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddHeatproof(u32 *priority);
BOOL CommonDamageRecoverCheck(BtlServerFlow *flow, u32 monId, u32 type);
void CommonTypeRecoverHP(BtlServerFlow *flow, u8 monId, u32 divisor);
void CommonTypeNoEffectRankUp(BtlServerFlow *flow, u8 monId, u32 stat, u32 amount);
void HandlerDrySkinDamageRecover(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerDrySkinCheck(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddDrySkin(u32 *priority);
void HandlerWaterAbsorbCheck(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddWaterAbsorb(u32 *priority);
void HandlerVoltAbsorbCheck(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddVoltAbsorb(u32 *priority);
void HandlerMotorDriveCheck(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddMotorDrive(u32 *priority);
void HandlerLevitate(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerLevitateTurnCheck(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddLevitate(u32 *priority);
void HandlerTruant(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerTruantGet(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerTruantFailed(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerTruantEndAction(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddTruant(u32 *priority);
BOOL func_ov167_021c09d0(BattleEventItem *item, BtlServerFlow *flow, u32 factorType, u32 event, u16 subId, u8 monId);
void HandlerMoldBreakerStart(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerMoldBreakerEnd(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerMoldBreakerConfirm(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddMoldBreaker(u32 *priority);
void CommonForecastOff(BattleEventItem *item, BtlServerFlow *flow, u8 monId);
void CommonForecastFormChange(BtlServerFlow *flow, u8 monId, u32 weather);
void HandlerForecastMemberOnField(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerForecastGetAbility(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerForecastWeather(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerForecastAirLock(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerForecastChangeAbility(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerDampEnd(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
BOOL HandlerDampSkipCheck(BattleEventItem *item, BtlServerFlow *flow, u32 factorType, u32 event, u16 subId, u8 monId);
void HandlerDampStart(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void func_ov167_021c06cc(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerDamp(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerDampEffective(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddDamp(u32 *priority);
void HandlerFlashFirePower(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerFlashFireRemove(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerFlashFireCheckNoEffect(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddFlashFire(u32 *priority);
void HandlerRunAway(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerRunAwayMessage(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddRunAway(u32 *priority);
void HandlerSoundproof(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddSoundproof(u32 *priority);
void HandlerLevitateAddImmunity(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerWonderGuard(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddWonderGuard(u32 *priority);
const BattleEventHandlerEntry *EventAddSturdy(u32 *priority);
void HandlerSturdyOneshotCheck(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerSturdyEndureCheck(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerSturdySurvive(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerDrySkinWeather(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerForecastAbilityOff(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddForecast(u32 *priority);
BOOL CommonMoveTargetChangeToMe(BtlServerFlow *flow, u8 monId, s32 *work, u32 type);
BOOL func_ov167_021abdd0(BtlServerFlow *flow, u8 attackerId, u8 defenderId, u16 move);
BOOL func_ov167_021c0d78(u16 move);
const BattleEventHandlerEntry *EventAddStormDrain(u32 *priority);
void HandlerStormDrain(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerStormDrainCheckNoEffect(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddLightningRod(u32 *priority);
void HandlerLightningRod(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerLightningRodStart(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerLightningRodCheckNoEffect(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddRegenerator(u32 *priority);
const BattleEventHandlerEntry *EventAddBigPecks(u32 *priority);
void HandlerBigPecksCheck(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerBigPecksGuard(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);

typedef struct AbilityEventAddEntry {
    u32 ability;
    const BattleEventHandlerEntry *(*eventAdd)(u32 *priority);
} AbilityEventAddEntry;

void HandlerSlowStartCalcSpeed(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerSlowStartAttackPower(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerSlowStartMemberIn(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void func_ov167_021be18c(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerSlowStartTextSet(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerSlowStartTurnCheck(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddSlowStart(u32 *priority);
void HandlerCuteCharm(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddCuteCharm(u32 *priority);
void HandlerEffectSpore(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddEffectSpore(u32 *priority);
void HandlerRoughSkin(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddRoughSkin(u32 *priority);
void HandlerAftermath(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddAftermath(u32 *priority);
void HandlerColorChange(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddColorChange(u32 *priority);
void HandlerSynchronize(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddSynchronize(u32 *priority);
void CommonContactStatusAbility(BtlServerFlow *flow, u32 monId, u32 status, BattleCondition condition, u8 chance);

void HandlerTrace(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerDownload(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddDownload(u32 *priority);
void HandlerForewarn(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddForewarn(u32 *priority);

void HandlerAnticipation(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
BOOL CheckAnticipationMon(BattleMon *mon, BattleMon *opponent);
const BattleEventHandlerEntry *EventAddAnticipation(u32 *priority);
void HandlerFrisk(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddFrisk(u32 *priority);
void HandlerBadDreams(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddBadDreams(u32 *priority);
void HandlerMoldBreakerMemberIn(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerSuctionCups(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddSuctionCups(u32 *priority);
void HandlerLiquidOoze(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerLiquidOozeFainted(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddLiquidOoze(u32 *priority);
BOOL HandlerKlutzSkipCheck(BattleEventItem *item, BtlServerFlow *flow, u32 factorType, u32 event, u16 subId, u8 monId);
void HandlerKlutzMemberInPrev(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerKlutzGetAbility(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerKlutzPreChange(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerKlutzGastroAcid(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerKlutzCheck(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerKlutzFail(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddKlutz(u32 *priority);
void HandlerStickyHoldNoEffect(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerStickyHold(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerStickyHoldReaction(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddStickyHold(u32 *priority);

const BattleEventHandlerEntry *EventAddPressure(u32 *priority);
void HandlerPressureMemberIn(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerPressure(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddMagicGuard(u32 *priority);
void HandlerMagicGuard(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddStench(u32 *priority);
void HandlerStench(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddShadowTag(u32 *priority);
void HandlerShadowTag(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddArenaTrap(u32 *priority);
void HandlerArenaTrap(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddMagnetPull(u32 *priority);
void HandlerMagnetPull(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddUnburden(u32 *priority);
void HandlerUnburdenBeforeItemSet(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerUnburdenSpeed(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddPickup(u32 *priority);
void HandlerPickup(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddPickpocket(u32 *priority);
void HandlerPickpocket(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerCursedBody(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddCursedBody(u32 *priority);

void HandlerWeakArmor(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddWeakArmor(u32 *priority);
void HandlerSheerForcePower(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerSheerForceCheckFail(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerSheerForceShrinkCheck(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerSheerForceHitCheck(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddSheerForce(u32 *priority);
BOOL IsAffectedBySheerForce(u16 move);
void HandlerDefiant(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddDefiant(u32 *priority);
void HandlerDefeatist(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddDefeatist(u32 *priority);
void HandlerMultiscale(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddMultiscale(u32 *priority);
void HandlerFriendGuard(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddFriendGuard(u32 *priority);
void HandlerHealer(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddHealer(u32 *priority);
void HandlerToxicBoost(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddToxicBoost(u32 *priority);
void HandlerFlareBoost(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddFlareBoost(u32 *priority);
void HandlerTelepathy(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddTelepathy(u32 *priority);

void HandlerMoody(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddMoody(u32 *priority);
void HandlerOvercoat(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddOvercoat(u32 *priority);
void HandlerPoisonTouch(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddPoisonTouch(u32 *priority);
void HandlerRegenerator(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddSandRush(u32 *priority);
void HandlerSandRush(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddWonderSkin(u32 *priority);
void HandlerWonderSkin(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddAnalytic(u32 *priority);
void HandlerAnalytic(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddSandForce(u32 *priority);
void HandlerSandForce(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerZenMode(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerZenModeGastroAcid(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddZenMode(u32 *priority);
BOOL HandlerInfiltratorSkipCheck(BattleEventItem *item, BtlServerFlow *flow, u32 factorType, u32 event, u16 subId,
                                 u8 monId);
void HandlerInfiltratorStart(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerInfiltratorEnd(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddInfiltrator(u32 *priority);
const BattleEventHandlerEntry *EventAddMoxie(u32 *priority);
void HandlerMoxie(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddJustified(u32 *priority);
void HandlerJustified(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddRattled(u32 *priority);
void HandlerRattled(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);

void HandlerMummy(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerSapSipperCheckNoEffect(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddSapSipper(u32 *priority);
void HandlerPrankster(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddPrankster(u32 *priority);
void HandlerMagicBounceCheck(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerMagicBounceWait(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerMagicBounceReflect(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddMagicBounce(u32 *priority);
void HandlerHarvest(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddHarvest(u32 *priority);
const BattleEventHandlerEntry *EventAddHeavyMetal(u32 *priority);
void HandlerHeavyMetal(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddLightMetal(u32 *priority);
void HandlerLightMetal(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerContrary(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddContrary(u32 *priority);
void HandlerUnnerveMemberIn(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerUnnerveRotationIn(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
BOOL HandlerUnnerveSkipCheck(BattleEventItem *item, BtlServerFlow *flow, u32 factorType, u32 event, u16 subId,
                             u8 monId);
const BattleEventHandlerEntry *EventAddUnnerve(u32 *priority);
void HandlerImposter(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
const BattleEventHandlerEntry *EventAddImposter(u32 *priority);
const BattleEventHandlerEntry *EventAddIllusion(u32 *priority);
void HandlerIllusionDamage(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerIllusionGastroAcid(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void HandlerIllusionChangeAbility(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);
void CommonIllusionBreak(BattleEventItem *item, BtlServerFlow *flow, u8 monId);
const BattleEventHandlerEntry *EventAddVictoryStar(u32 *priority);
void HandlerVictoryStar(BattleEventItem *item, BtlServerFlow *flow, u8 monId, s32 *work);

const BattleEventHandlerEntry *EventAddMummy(u32 *priority);

#endif // POKEBW2_BATTLE_BTL_ABILITY_H
