#!/usr/bin/env python3
"""Generate a constants header from a name list in data/constants/.

    gen_constants.py data/constants/species.txt build/include/generated/constants/species.h

The lists are the source of truth for the game's ID constants and are meant to be edited, by hand or by mods. Each
line is a constant's full name, taking the previous value plus one, or `NAME = value` to set the value (decimal or
hex). `#` starts a comment. The build generates the headers from the lists (see configure.py), and the scripts read
the lists through load() here, so C code, data files and tools all share the same names.
"""
import argparse
import re
import sys
from pathlib import Path

LISTS_DIR = Path(__file__).parents[2] / "data" / "constants"


def parse(path: Path) -> dict[str, int]:
    """Returns the constants of a list file, by name, in file order."""
    names: dict[str, int] = {}
    value = -1
    for number, raw in enumerate(path.read_text().splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        name, _, given = line.partition("=")
        name = name.strip()
        value = int(given.strip(), 0) if given else value + 1
        if not name.isidentifier():
            sys.exit(f"{path}:{number}: {name!r} is not a valid name")
        if name in names:
            sys.exit(f"{path}:{number}: {name} is already {names[name]}")
        names[name] = value
    return names


def ordered_names(name: str) -> list[str]:
    """Returns the constants of a list in value order, the first of each value, which must run from 0 without gaps."""
    first: dict[int, str] = {}
    for constant, number in load(name).items():
        first.setdefault(number, constant)
    if sorted(first) != list(range(len(first))):
        sys.exit(f"{name}.txt doesn't number its constants from 0 without gaps")
    return [first[number] for number in range(len(first))]


def ordered_files(name: str, prefix: str, directory: Path, suffix: str) -> list[Path]:
    """Returns the files named after a list's constants, <constant less the prefix, in lower case><suffix>, in the
    list's order: the order of the archive they make."""
    return [directory / (constant.removeprefix(prefix).lower() + suffix) for constant in ordered_names(name)]


def load(name: str) -> dict[str, int]:
    """Returns the constants of data/constants/<name>.txt, for the scripts."""
    return parse(LISTS_DIR / f"{name}.txt")


def generate(source: Path) -> str:
    """Returns the header generated from a list."""
    names = parse(source)
    hexadecimal = any(line.split("=")[-1].strip().startswith("0x")
                      for line in source.read_text().splitlines() if "=" in line.split("#")[0])
    guard = f"POKEBW2_CONSTANTS_{source.stem.upper()}_H"
    relative = source.resolve().relative_to(LISTS_DIR.parents[1]).as_posix()
    lines = [
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        f"// Generated by tools/scripts/gen_constants.py from {relative}, edit that instead",
        "",
        *(f"#define {name} {value:#x}" if hexadecimal else f"#define {name} {value}"
          for name, value in names.items()),
        "",
        f"#endif // {guard}",
        "",
    ]
    return "\n".join(lines)


def header_text(header: str) -> str:
    """Returns the text of a header as the code includes it, such as "constants/species.h": generated from its list if
    it has one, so that the scripts need no build first, or else read from include/."""
    path = Path(header)
    if path.parent == Path("constants") and (LISTS_DIR / f"{path.stem}.txt").exists():
        return generate(LISTS_DIR / f"{path.stem}.txt")
    return (LISTS_DIR.parents[1] / "include" / header).read_text()


def constant_names(header: str, prefix: str) -> dict[int, str]:
    """Returns the first name of each value of the constants with a prefix in a constants header."""
    names = {}
    for match in re.finditer(rf"^#define ({prefix}\w+) (0x[0-9a-fA-F]+|\d+)(?:\s*//.*)?$",
                             header_text(f"constants/{header}"), re.MULTILINE):
        names.setdefault(int(match.group(2), 0), match.group(1))
    return names


def flag_names(header: str, prefix: str, flags: int) -> str:
    """Returns flags as an OR of the constants with a prefix, defined as (1 << N) in a constants header."""
    names = {}
    for match in re.finditer(rf"^#define ({prefix}\w+) \(1 << (\d+)\)", header_text(f"constants/{header}"), re.M):
        names[int(match.group(2))] = match.group(1)
    parts = [names.get(bit, f"(1 << {bit})") for bit in range(32) if flags >> bit & 1]
    return " | ".join(parts) if parts else "0"


def name(names: dict[int, str], value: int) -> str:
    return names.get(value, str(value))


def write_header(source: Path, output: Path):
    """Writes the header only if it changed, so that with restat the build doesn't recompile everything that includes
    it whenever a list or this script is touched."""
    text = generate(source)
    if output.exists() and output.read_text() == text:
        return
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("source", type=Path, help="the list, such as data/constants/species.txt")
    parser.add_argument("output", type=Path, help="the header to write")
    args = parser.parse_args()
    write_header(args.source, args.output)


if __name__ == "__main__":
    main()
