#!/usr/bin/env python3
"""Write the header of a message file's IDs, which the build makes for every file of data/text/:

    text_ids.py data/text/script/black_city.txt build/include/generated/text/script/black_city.h

Each message line's ID (see text_data.py) becomes a define of the message's number in its file, counting the messages
that a \\from line stands for, so the code and the scripts include text/<archive>/<bank>.h and name their messages.
"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from datajson import DataError  # noqa: E402
from text_data import FROM, split_message  # noqa: E402
from text_sources import expand  # noqa: E402


def message_numbers(path: Path) -> list[tuple[str, int]]:
    return count_messages(path)[0]


def message_count(path: Path) -> int:
    """The number of messages in the file, counting the ones its \\from lines stand for."""
    return count_messages(path)[1]


def count_messages(path: Path) -> tuple[list[tuple[str, int]], int]:
    numbers = []
    index = 0
    for line in path.read_text(encoding="utf-8").split("\n")[:-1]:
        match = FROM.fullmatch(line)
        if match:
            index += len(expand(match[1]))
            continue
        message_id, _ = split_message(line)
        if message_id is not None:
            numbers.append((message_id, index))
            index += 1
    return numbers, index


def header(path: Path) -> str:
    guard = f"POKEBW2_TEXT_{path.parent.name.upper()}_{path.stem.upper()}_H"
    relative = f"data/text/{path.parent.name}/{path.name}"
    lines = [f"#ifndef {guard}", f"#define {guard}", "",
             f"// Generated by tools/scripts/text_ids.py from {relative}, edit that instead", ""]
    lines += [f"#define {message_id} {index}" for message_id, index in message_numbers(path)]
    lines += ["", f"#endif // {guard}", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    try:
        text = header(args.source)
    except (DataError, ValueError) as error:
        sys.exit(f"error: {args.source}: {error}")
    # Written only when it changes, so that with restat nothing that includes it recompiles needlessly
    if args.output.exists() and args.output.read_text() == text:
        return
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text)


if __name__ == "__main__":
    main()
