#!/usr/bin/env python3
"""Import names from the swan symbol databases (https://github.com/ds-pokemon-hacking/swan).

Names from IRDO.yml (White 2) and IREO.yml (Black 2) are applied to symbols that start exactly at the named address
in that version, then carried over to the other version through the pairs made by version_map.py. Names that look
generated by IDA (sub_, loc_, dword_ and so on) are skipped, and only symbols with default dsd names are renamed.

Afterwards, every paired symbol in the other version is renamed to the primary version's name, so the same source
files can be built for both versions. References in src/ and include/ are updated too.
"""
import argparse
import csv
import re
import sys
from collections import defaultdict
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from tools.decomp.dsd_config import ROOT, load_modules  # noqa: E402

GENERATED_NAME_RE = re.compile(
    r"^(sub|nullsub|loc|locret|off|dword|word|byte|unk|stru|asc|jpt|def|flt|dbl|j)_|^a[A-Z0-9]\w*$"
)
IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
# Default names, optionally with a suffix such as `_unk` or a version tag for symbols without a counterpart
DEFAULT_NAME_RE = re.compile(r"^(func|data)_(ov\d{3}_)?[0-9a-f]{8}(_[a-z]\w*)?$")
SYMBOL_LINE_RE = re.compile(r"^(\S+) (kind:\S+) addr:(0x[0-9a-f]+)(.*)$")

FUNCTION, OTHER = "function", "other"


def swan_module(segment: str) -> str | None:
    """Returns the dsd module path of a swan segment, or `None` for segments outside the ARM9 modules."""
    if segment in ("ARM9", "ARM9_DATA", "ARM9_BSS"):
        return "."
    if segment == "ITCM":
        return "itcm"
    match = re.match(r"^OVL_(\d+)(_BSS)?$", segment)
    if match:
        return f"overlays/ov{int(match.group(1)):03d}"
    return None


def load_swan(path: Path):
    """Yields (module, address, name) for every usable name in a swan database."""
    database = yaml.safe_load(path.read_text())
    segments = {segment["ID"]: segment["Name"] for segment in database["Segments"]}
    counts = defaultdict(int)
    for symbol in database["Symbols"]:
        counts[symbol["Name"]] += 1
    for symbol in database["Symbols"]:
        name = symbol["Name"]
        module = swan_module(segments[symbol["Segment"]])
        if module is None or counts[name] > 1 or GENERATED_NAME_RE.match(name) or not IDENTIFIER_RE.match(name):
            continue
        yield module, symbol["Address"], name


def load_pairs(path: Path, primary: str, other: str):
    """Returns address pairs per version and module: pairs[version][module][addr] = addr in the other version."""
    pairs = {primary: defaultdict(dict), other: defaultdict(dict)}
    with path.open() as f:
        for row in csv.DictReader(f, delimiter="\t"):
            primary_addr = int(row[f"{primary}_addr"], 16)
            other_addr = int(row[f"{other}_addr"], 16)
            pairs[primary][row["module"]][primary_addr] = other_addr
            pairs[other][row["module"]][other_addr] = primary_addr
    return pairs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("swan", type=Path, help="path to a clone of the swan repository")
    parser.add_argument("--primary", default="b2_us")
    parser.add_argument("--other", default="w2_us")
    parser.add_argument("--map", type=Path, required=True, help="function pairs made by version_map.py")
    parser.add_argument("--symbols-map", type=Path, required=True, help="other symbol pairs made by version_map.py")
    parser.add_argument("--dry", action="store_true", help="only report what would change")
    args = parser.parse_args()

    primary, other = args.primary, args.other
    versions = {primary: load_modules(primary), other: load_modules(other)}
    sources = {primary: args.swan / "IREO.yml", other: args.swan / "IRDO.yml"}
    pairs = {FUNCTION: load_pairs(args.map, primary, other), OTHER: load_pairs(args.symbols_map, primary, other)}

    def symbol_kind(symbol) -> str:
        return FUNCTION if symbol.kind == "function" else OTHER

    def to_primary(version, kind, module, addr):
        return addr if version == primary else pairs[kind][version][module].get(addr)

    # Names by (kind, module, primary address). The White 2 database is applied last, so it wins conflicts.
    names: dict[tuple[str, str, int], str] = {}
    stats = defaultdict(int)
    for version in (primary, other):
        functions = {name: {f.addr: f for f in m.functions()} for name, m in versions[version].items()}
        others = {name: {s.addr: s for s in m.symbols if s.kind != "function"} for name, m in versions[version].items()}
        for module, address, name in load_swan(sources[version]):
            function = functions.get(module, {}).get(address & ~1)
            if function is not None and not (address & 1 and not function.thumb):
                kind, addr = FUNCTION, function.addr
            elif address in others.get(module, {}):
                kind, addr = OTHER, address
            else:
                stats[f"{version}: no symbol at address"] += 1
                continue
            primary_addr = to_primary(version, kind, module, addr)
            if primary_addr is None:
                stats[f"{version}: {kind} not paired between versions"] += 1
                continue
            key = (kind, module, primary_addr)
            if key in names and names[key] != name:
                stats["renamed by White 2 database"] += 1
            names[key] = name
            stats[f"{version}: {kind} names applied"] += 1

    # A name used for two different symbols is ambiguous, drop it entirely
    by_name = defaultdict(list)
    for key, name in names.items():
        by_name[name].append(key)
    for name, keys in by_name.items():
        if len(keys) > 1:
            stats["dropped, name used for several symbols"] += len(keys)
            for key in keys:
                del names[key]

    # Final primary names. Only default names are replaced, dsd relies on some of its own names such as Entry.
    primary_names: dict[tuple[str, str, int], str] = {}
    existing_names = defaultdict(set)
    for module_name, module in versions[primary].items():
        for symbol in module.symbols:
            existing_names[symbol.name].add((symbol_kind(symbol), module_name, symbol.addr))
    renames = {}  # old primary name -> new name, for source files
    for module_name, module in versions[primary].items():
        for symbol in module.symbols:
            key = (symbol_kind(symbol), module_name, symbol.addr)
            new_name = names.get(key)
            if new_name is None or not DEFAULT_NAME_RE.match(symbol.name):
                continue
            if existing_names.get(new_name, {key}) != {key}:
                stats["dropped, collides with an existing name"] += 1
                continue
            primary_names[key] = new_name
            renames[symbol.name] = new_name

    # Rename both versions. Paired symbols in the other version get the primary version's name.
    changed = defaultdict(int)
    for version, modules in versions.items():
        primary_modules = versions[primary]
        for module_name, module in modules.items():
            path = module.config_dir / "symbols.txt"
            if not path.exists():
                continue
            primary_symbols = {(symbol_kind(s), s.addr): s.name for s in primary_modules[module_name].symbols}
            new_names = {}
            for symbol in module.symbols:
                kind = symbol_kind(symbol)
                primary_addr = to_primary(version, kind, module_name, symbol.addr)
                if not DEFAULT_NAME_RE.match(symbol.name):
                    continue
                if primary_addr is None:
                    # No counterpart in the primary version, so tag the name to keep it apart from primary names
                    if version != primary and not symbol.name.endswith(f"_{version}"):
                        new_names[(kind, symbol.addr)] = f"{symbol.name}_{version}"
                    continue
                key = (kind, module_name, primary_addr)
                new_name = primary_names.get(key, primary_symbols.get((kind, primary_addr)))
                if new_name and new_name != symbol.name:
                    new_names[(kind, symbol.addr)] = new_name
            if not new_names:
                continue
            lines = path.read_text().splitlines()
            for i, line in enumerate(lines):
                match = SYMBOL_LINE_RE.match(line)
                if not match:
                    continue
                kind = FUNCTION if match.group(2).startswith("kind:function") else OTHER
                new_name = new_names.get((kind, int(match.group(3), 16)))
                if new_name:
                    lines[i] = f"{new_name} {match.group(2)} addr:{match.group(3)}{match.group(4)}"
                    changed[version] += 1
            if not args.dry:
                path.write_text("\n".join(lines) + "\n")

    # Every version must still have unique names, as all modules are linked together
    for version, modules in versions.items():
        seen = defaultdict(list)
        for module_name, module in modules.items():
            path = module.config_dir / "symbols.txt"
            if not path.exists():
                continue
            lines = path.read_text().splitlines() if not args.dry else []
            for line in lines:
                match = SYMBOL_LINE_RE.match(line)
                if match and not match.group(4).endswith(" local") and not match.group(1).startswith("."):
                    seen[match.group(1)].append((module_name, match.group(3)))
        duplicates = {name: where for name, where in seen.items() if len(where) > 1}
        if duplicates:
            print(f"{version}: {len(duplicates)} duplicate names, e.g. {list(duplicates.items())[:3]}")

    # Update references in source files
    source_changes = 0
    if renames:
        pattern = re.compile(r"\b(" + "|".join(re.escape(old) for old in renames) + r")\b")
        for source in [p for d in ("src", "include", "lib") for p in (ROOT / d).rglob("*.[ch]")]:
            text = source.read_text()
            new_text = pattern.sub(lambda m: renames[m.group(1)], text)
            if new_text != text:
                source_changes += 1
                if not args.dry:
                    source.write_text(new_text)

    for key, count in sorted(stats.items()):
        print(f"{key}: {count}")
    named = defaultdict(int)
    for kind, _, _ in primary_names:
        named[kind] += 1
    print(f"named from swan: {named[FUNCTION]} functions, {named[OTHER]} other symbols")
    for version, count in changed.items():
        print(f"{version}: renamed {count} symbols")
    print(f"source files updated: {source_changes}")


if __name__ == "__main__":
    sys.exit(main())
