#!/usr/bin/env python3
"""Write constants/pms_words.h, the easy chat (PMS) words, which the build makes from the word categories' message files:

    pms_words.py build/include/generated/constants/pms_words.h

A word is a message of one of the categories' files, numbered across the categories in the order of pms_word.c's
sCategoryMsgFiles, which CATEGORIES gives too. The header gives each category its index, its first word and its count
(PMS_WORD_CATEGORY_GREETINGS, PMS_WORD_FIRST_GREETINGS, PMS_WORD_COUNT_GREETINGS), a word of a species, move, type or
ability by its constant (PMS_WORD_SPECIES(SPECIES_PIKACHU)), and every other word by its category and message ID
(PMS_WORD_GREETINGS_HELLO for PmsWordsGreetings_Text_Hello). Adding a word to a category's file renumbers the words
after it, as the game numbers them.
"""
import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from tools.data.datajson import DataError  # noqa: E402
from tools.text.text_data import FROM, split_message  # noqa: E402
from tools.text.text_ids import message_count, message_numbers  # noqa: E402
from tools.text.text_sources import expand  # noqa: E402

ROOT = Path(__file__).parents[2]
TEXT = ROOT / "data/text/system"
# The last word of a category whose file goes on past its words, with padding
LAST_WORDS = {"SPECIES": "SpeciesNamesUpper_Text_BadEgg"}
# The categories in word order: their name, their message file, and for one whose words are another constant's, the
# macro that turns one into its word
CATEGORIES = [
    ("SPECIES", "species_names_upper", "PMS_WORD_SPECIES(species)"),  # Up to LAST_WORDS's, the egg and the bad egg
    ("MOVES", "move_names_upper", "PMS_WORD_MOVE(move)"),
    ("TYPES", "type_names_upper", "PMS_WORD_TYPE(type)"),
    ("ABILITIES", "ability_names_upper", "PMS_WORD_ABILITY(ability)"),
    ("TRAINER", "pms_words_trainer", None),
    ("PEOPLE", "pms_words_people", None),
    ("GREETINGS", "pms_words_greetings", None),
    ("LIFESTYLE", "pms_words_lifestyle", None),
    ("FEELINGS", "pms_words_feelings", None),
    ("TERM", "pms_words_term", None),
    ("CONNECTION", "pms_words_connection", None),
    ("ANIMATED", "pms_words_animated", None),
    ("VOICE", "pms_words_voice", None),
]


def constants_end(path: Path) -> int:
    """The number of the first message after the file's last \\from line, which stands for the constants'."""
    index = end = 0
    for line in path.read_text(encoding="utf-8").split("\n")[:-1]:
        match = FROM.fullmatch(line)
        if match:
            index += len(expand(match[1]))
            end = index
        elif split_message(line)[0] is not None:
            index += 1
    return end


def constant(message_id: str) -> str:
    word = message_id.split("_Text_", 1)[1]
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])", "_", word).upper()


def header() -> str:
    guard = "POKEBW2_CONSTANTS_PMS_WORDS_H"
    lines = [f"#ifndef {guard}", f"#define {guard}", "",
             "// Generated by tools/text/pms_words.py from the word categories' message files, edit those instead", ""]
    words = []
    first = 0
    for index, (category, file, macro) in enumerate(CATEGORIES):
        path = TEXT / f"{file}.txt"
        count = message_count(path)
        if category in LAST_WORDS:
            count = dict(message_numbers(path))[LAST_WORDS[category]] + 1
        lines += [f"#define PMS_WORD_CATEGORY_{category} {index}", f"#define PMS_WORD_FIRST_{category} {first}",
                  f"#define PMS_WORD_COUNT_{category} {count}"]
        named = message_numbers(path)
        if macro:
            parameter = macro[macro.index("(") + 1:-1]
            lines.append(f"#define {macro} (PMS_WORD_FIRST_{category} + ({parameter}))")
            # Its own messages after the constants' are words too, the eggs after the species
            named = [(message_id, number) for message_id, number in named if constants_end(path) <= number < count]
        words += [f"#define PMS_WORD_{category}_{constant(message_id)} {first + number}" for message_id, number in named]
        first += count
    lines += [f"#define PMS_WORD_TOTAL {first}", "", *words, "", f"#endif // {guard}", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    try:
        text = header()
    except (DataError, ValueError) as error:
        sys.exit(f"error: {error}")
    # Written only when it changes, so that with restat nothing that includes it recompiles needlessly
    if args.output.exists() and args.output.read_text() == text:
        return
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text)


if __name__ == "__main__":
    main()
